# Generated by Django 3.2.6 on 2021-09-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered',
        ),
    ]
