# Generated by Django 3.2.6 on 2021-09-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20210902_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
