# Generated by Django 3.2.6 on 2021-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.CharField(max_length=64, verbose_name='human_id')),
                ('site_name', models.CharField(max_length=64, verbose_name='site_name')),
                ('site_password', models.CharField(max_length=15, verbose_name='site_password')),
            ],
        ),
        migrations.AlterField(
            model_name='human',
            name='human_password',
            field=models.CharField(max_length=64, verbose_name='human_password'),
        ),
    ]
